spring:
  profiles.active: prod
  thymeleaf:
    cache: false
    mode: HTML5
---
spring:
  profiles: dev

  data:
    mongodb:
      port: 0

---
spring:
   profiles: prod

   data:
    mongodb:
          uri: mongodb://wishuser:wishpassword@ds061355.mongolab.com:61355/wishdb
